// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Options {
    "Method": string;
    "URLs": string[];
    "Paths": string[];
    "Workers": number;
    "Timeout": number;
    "BodyExclude": string;

    /**
     * 过滤响应包长度数据次数出现了多少次，就过滤相同的
     */
    "BodyLengthExcludeTimes": number;
    "StatusCodeExclude": number[];
    "Redirect": boolean;
    "Interval": number;
    "CustomHeader": string;
    "Recursion": number;
    "Backupscan": boolean;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("Method" in $$source)) {
            this["Method"] = "";
        }
        if (!("URLs" in $$source)) {
            this["URLs"] = [];
        }
        if (!("Paths" in $$source)) {
            this["Paths"] = [];
        }
        if (!("Workers" in $$source)) {
            this["Workers"] = 0;
        }
        if (!("Timeout" in $$source)) {
            this["Timeout"] = 0;
        }
        if (!("BodyExclude" in $$source)) {
            this["BodyExclude"] = "";
        }
        if (!("BodyLengthExcludeTimes" in $$source)) {
            this["BodyLengthExcludeTimes"] = 0;
        }
        if (!("StatusCodeExclude" in $$source)) {
            this["StatusCodeExclude"] = [];
        }
        if (!("Redirect" in $$source)) {
            this["Redirect"] = false;
        }
        if (!("Interval" in $$source)) {
            this["Interval"] = 0;
        }
        if (!("CustomHeader" in $$source)) {
            this["CustomHeader"] = "";
        }
        if (!("Recursion" in $$source)) {
            this["Recursion"] = 0;
        }
        if (!("Backupscan" in $$source)) {
            this["Backupscan"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("URLs" in $$parsedSource) {
            $$parsedSource["URLs"] = $$createField1_0($$parsedSource["URLs"]);
        }
        if ("Paths" in $$parsedSource) {
            $$parsedSource["Paths"] = $$createField2_0($$parsedSource["Paths"]);
        }
        if ("StatusCodeExclude" in $$parsedSource) {
            $$parsedSource["StatusCodeExclude"] = $$createField7_0($$parsedSource["StatusCodeExclude"]);
        }
        return new Options($$parsedSource as Partial<Options>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
