version: '3'

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml

vars:
  APP_NAME: "Slack"
  BIN_DIR: "build/bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: darwin:build

  package:
    summary: Packages a production build of the application
    cmds:
      - task: darwin:package

  run:
    summary: Runs the application
    cmds:
      - task: darwin:run

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
