// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as structs$0 from "../../lib/structs/models.js";

/**
 * 杀软识别
 */
export function AntivirusIdentify(tasklist: string): $CancellablePromise<structs$0.AntivirusResult[]> {
    return $Call.ByID(2445397652, tasklist).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ConnectAndExecute(protocol: string, ip: string, port: string, username: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(3809648271, protocol, ip, port, username, password);
}

export function ExtractAlibabaDruidWebSession(input: string): $CancellablePromise<string[]> {
    return $Call.ByID(3941724554, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ExtractAlibabaDruidWebURI(input: string): $CancellablePromise<string[]> {
    return $Call.ByID(1074460360, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ExtractIP(text: string): $CancellablePromise<string> {
    return $Call.ByID(647389665, text);
}

export function ExtractURLs(input: string): $CancellablePromise<string[]> {
    return $Call.ByID(2516763302, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function FormatOutput(content: string): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(1278037441, content).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GOOS(): $CancellablePromise<string> {
    return $Call.ByID(1368989891);
}

export function GetToken(baseURL: string, appkey: string, appsecret: string, xforwordfor: string, proxyURL: string): $CancellablePromise<string> {
    return $Call.ByID(2023388410, baseURL, appkey, appsecret, xforwordfor, proxyURL);
}

export function IPParse(ipList: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(805515933, ipList).then(($result: any) => {
        return $$createType2($result);
    });
}

export function IsRoot(): $CancellablePromise<boolean> {
    return $Call.ByID(1349770747);
}

/**
 * 补丁识别
 */
export function PatchIdentify(systeminfo: string): $CancellablePromise<structs$0.AuthPatch[]> {
    return $Call.ByID(3717282199, systeminfo).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PortParse(text: string): $CancellablePromise<number[]> {
    return $Call.ByID(1886871211, text).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = structs$0.AntivirusResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = structs$0.AuthPatch.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
