// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AntivirusResult {
    "Process": string;
    "Pid": string;
    "Name": string;

    /** Creates a new AntivirusResult instance. */
    constructor($$source: Partial<AntivirusResult> = {}) {
        if (!("Process" in $$source)) {
            this["Process"] = "";
        }
        if (!("Pid" in $$source)) {
            this["Pid"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AntivirusResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AntivirusResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AntivirusResult($$parsedSource as Partial<AntivirusResult>);
    }
}

export class App {
    "cityId": number;
    "countyId": number;
    "dataId": number;
    "leaderName": string;
    "mainId": string;
    "mainLicence": string;
    "mainUnitAddress": string;
    "mainUnitCertNo": string;
    "mainUnitCertType": number;
    "natureId": number;
    "natureName": string;
    "provinceId": number;
    "serviceId": number;
    "serviceLicence": string;
    "serviceName": string;
    "serviceType": number;
    "unitName": string;
    "updateRecordTime": string;
    "version": string;

    /** Creates a new App instance. */
    constructor($$source: Partial<App> = {}) {
        if (!("cityId" in $$source)) {
            this["cityId"] = 0;
        }
        if (!("countyId" in $$source)) {
            this["countyId"] = 0;
        }
        if (!("dataId" in $$source)) {
            this["dataId"] = 0;
        }
        if (!("leaderName" in $$source)) {
            this["leaderName"] = "";
        }
        if (!("mainId" in $$source)) {
            this["mainId"] = "";
        }
        if (!("mainLicence" in $$source)) {
            this["mainLicence"] = "";
        }
        if (!("mainUnitAddress" in $$source)) {
            this["mainUnitAddress"] = "";
        }
        if (!("mainUnitCertNo" in $$source)) {
            this["mainUnitCertNo"] = "";
        }
        if (!("mainUnitCertType" in $$source)) {
            this["mainUnitCertType"] = 0;
        }
        if (!("natureId" in $$source)) {
            this["natureId"] = 0;
        }
        if (!("natureName" in $$source)) {
            this["natureName"] = "";
        }
        if (!("provinceId" in $$source)) {
            this["provinceId"] = 0;
        }
        if (!("serviceId" in $$source)) {
            this["serviceId"] = 0;
        }
        if (!("serviceLicence" in $$source)) {
            this["serviceLicence"] = "";
        }
        if (!("serviceName" in $$source)) {
            this["serviceName"] = "";
        }
        if (!("serviceType" in $$source)) {
            this["serviceType"] = 0;
        }
        if (!("unitName" in $$source)) {
            this["unitName"] = "";
        }
        if (!("updateRecordTime" in $$source)) {
            this["updateRecordTime"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new App instance from a string or object.
     */
    static createFrom($$source: any = {}): App {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new App($$parsedSource as Partial<App>);
    }
}

export class Applet {
    "cityId": number;
    "countyId": number;
    "dataId": number;
    "leaderName": string;
    "mainId": string;
    "mainLicence": string;
    "mainUnitAddress": string;
    "mainUnitCertNo": string;
    "mainUnitCertType": number;
    "natureId": number;
    "natureName": string;
    "provinceId": number;
    "serviceId": number;
    "serviceLicence": string;
    "serviceName": string;
    "serviceType": number;
    "unitName": string;
    "updateRecordTime": string;
    "version": string;

    /** Creates a new Applet instance. */
    constructor($$source: Partial<Applet> = {}) {
        if (!("cityId" in $$source)) {
            this["cityId"] = 0;
        }
        if (!("countyId" in $$source)) {
            this["countyId"] = 0;
        }
        if (!("dataId" in $$source)) {
            this["dataId"] = 0;
        }
        if (!("leaderName" in $$source)) {
            this["leaderName"] = "";
        }
        if (!("mainId" in $$source)) {
            this["mainId"] = "";
        }
        if (!("mainLicence" in $$source)) {
            this["mainLicence"] = "";
        }
        if (!("mainUnitAddress" in $$source)) {
            this["mainUnitAddress"] = "";
        }
        if (!("mainUnitCertNo" in $$source)) {
            this["mainUnitCertNo"] = "";
        }
        if (!("mainUnitCertType" in $$source)) {
            this["mainUnitCertType"] = 0;
        }
        if (!("natureId" in $$source)) {
            this["natureId"] = 0;
        }
        if (!("natureName" in $$source)) {
            this["natureName"] = "";
        }
        if (!("provinceId" in $$source)) {
            this["provinceId"] = 0;
        }
        if (!("serviceId" in $$source)) {
            this["serviceId"] = 0;
        }
        if (!("serviceLicence" in $$source)) {
            this["serviceLicence"] = "";
        }
        if (!("serviceName" in $$source)) {
            this["serviceName"] = "";
        }
        if (!("serviceType" in $$source)) {
            this["serviceType"] = 0;
        }
        if (!("unitName" in $$source)) {
            this["unitName"] = "";
        }
        if (!("updateRecordTime" in $$source)) {
            this["updateRecordTime"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Applet instance from a string or object.
     */
    static createFrom($$source: any = {}): Applet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Applet($$parsedSource as Partial<Applet>);
    }
}

export class AuthPatch {
    "MS": string;
    "Patch": string;
    "Description": string;
    "System": string;
    "Reference": string;

    /** Creates a new AuthPatch instance. */
    constructor($$source: Partial<AuthPatch> = {}) {
        if (!("MS" in $$source)) {
            this["MS"] = "";
        }
        if (!("Patch" in $$source)) {
            this["Patch"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("System" in $$source)) {
            this["System"] = "";
        }
        if (!("Reference" in $$source)) {
            this["Reference"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthPatch instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthPatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthPatch($$parsedSource as Partial<AuthPatch>);
    }
}

export class Children {
    "Name": string;
    "Type": string;
    "Path": string;
    "Target": string;

    /**
     * 纯图标路径
     */
    "Favicon": string;

    /**
     * JDK环境变量
     */
    "Jdk": string;

    /** Creates a new Children instance. */
    constructor($$source: Partial<Children> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Target" in $$source)) {
            this["Target"] = "";
        }
        if (!("Favicon" in $$source)) {
            this["Favicon"] = "";
        }
        if (!("Jdk" in $$source)) {
            this["Jdk"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Children instance from a string or object.
     */
    static createFrom($$source: any = {}): Children {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Children($$parsedSource as Partial<Children>);
    }
}

export class CompanyInfo {
    "CompanyName": string;

    /**
     * 商标
     */
    "Trademark": string;

    /**
     * 投资比例
     */
    "Investment": string;

    /**
     * 注册资金
     */
    "Amount": string;

    /**
     * 注册状态
     */
    "RegStatus": string;
    "Domains": string[];
    "Subsidiaries": CompanyInfo[];

    /**
     * App
     */
    "Apps": App[];

    /**
     * 小程序
     */
    "Applets": Applet[];

    /**
     * 公众号
     */
    "OfficialAccounts": OfficialAccount[];

    /** Creates a new CompanyInfo instance. */
    constructor($$source: Partial<CompanyInfo> = {}) {
        if (!("CompanyName" in $$source)) {
            this["CompanyName"] = "";
        }
        if (!("Trademark" in $$source)) {
            this["Trademark"] = "";
        }
        if (!("Investment" in $$source)) {
            this["Investment"] = "";
        }
        if (!("Amount" in $$source)) {
            this["Amount"] = "";
        }
        if (!("RegStatus" in $$source)) {
            this["RegStatus"] = "";
        }
        if (!("Domains" in $$source)) {
            this["Domains"] = [];
        }
        if (!("Subsidiaries" in $$source)) {
            this["Subsidiaries"] = [];
        }
        if (!("Apps" in $$source)) {
            this["Apps"] = [];
        }
        if (!("Applets" in $$source)) {
            this["Applets"] = [];
        }
        if (!("OfficialAccounts" in $$source)) {
            this["OfficialAccounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompanyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CompanyInfo {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType6;
        const $$createField9_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Domains" in $$parsedSource) {
            $$parsedSource["Domains"] = $$createField5_0($$parsedSource["Domains"]);
        }
        if ("Subsidiaries" in $$parsedSource) {
            $$parsedSource["Subsidiaries"] = $$createField6_0($$parsedSource["Subsidiaries"]);
        }
        if ("Apps" in $$parsedSource) {
            $$parsedSource["Apps"] = $$createField7_0($$parsedSource["Apps"]);
        }
        if ("Applets" in $$parsedSource) {
            $$parsedSource["Applets"] = $$createField8_0($$parsedSource["Applets"]);
        }
        if ("OfficialAccounts" in $$parsedSource) {
            $$parsedSource["OfficialAccounts"] = $$createField9_0($$parsedSource["OfficialAccounts"]);
        }
        return new CompanyInfo($$parsedSource as Partial<CompanyInfo>);
    }
}

export class Data {
    "name": string;
    "company": string;
    "r_code": string;

    /** Creates a new Data instance. */
    constructor($$source: Partial<Data> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("r_code" in $$source)) {
            this["r_code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Data instance from a string or object.
     */
    static createFrom($$source: any = {}): Data {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Data($$parsedSource as Partial<Data>);
    }
}

export class DataSource {
    "Tianyancha": Tianyancha;
    "Miit": Miit;

    /** Creates a new DataSource instance. */
    constructor($$source: Partial<DataSource> = {}) {
        if (!("Tianyancha" in $$source)) {
            this["Tianyancha"] = (new Tianyancha());
        }
        if (!("Miit" in $$source)) {
            this["Miit"] = (new Miit());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSource instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSource {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tianyancha" in $$parsedSource) {
            $$parsedSource["Tianyancha"] = $$createField0_0($$parsedSource["Tianyancha"]);
        }
        if ("Miit" in $$parsedSource) {
            $$parsedSource["Miit"] = $$createField1_0($$parsedSource["Miit"]);
        }
        return new DataSource($$parsedSource as Partial<DataSource>);
    }
}

export class DatabaseConnection {
    "Nanoid": string;
    "Scheme": string;
    "Host": string;
    "Port": number;
    "Username": string;
    "Password": string;

    /**
     * Oracle 的服务名称
     */
    "ServerName": string;
    "Notes": string;

    /** Creates a new DatabaseConnection instance. */
    constructor($$source: Partial<DatabaseConnection> = {}) {
        if (!("Nanoid" in $$source)) {
            this["Nanoid"] = "";
        }
        if (!("Scheme" in $$source)) {
            this["Scheme"] = "";
        }
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("Username" in $$source)) {
            this["Username"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }
        if (!("ServerName" in $$source)) {
            this["ServerName"] = "";
        }
        if (!("Notes" in $$source)) {
            this["Notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseConnection($$parsedSource as Partial<DatabaseConnection>);
    }
}

export class FindSomething {
    "JS": InfoSource[];
    "APIRoute": InfoSource[];
    "IP_URL": InfoSource[];
    "IDCard": InfoSource[];
    "Phone": InfoSource[];
    "Email": InfoSource[];
    "Sensitive": InfoSource[];

    /** Creates a new FindSomething instance. */
    constructor($$source: Partial<FindSomething> = {}) {
        if (!("JS" in $$source)) {
            this["JS"] = [];
        }
        if (!("APIRoute" in $$source)) {
            this["APIRoute"] = [];
        }
        if (!("IP_URL" in $$source)) {
            this["IP_URL"] = [];
        }
        if (!("IDCard" in $$source)) {
            this["IDCard"] = [];
        }
        if (!("Phone" in $$source)) {
            this["Phone"] = [];
        }
        if (!("Email" in $$source)) {
            this["Email"] = [];
        }
        if (!("Sensitive" in $$source)) {
            this["Sensitive"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FindSomething instance from a string or object.
     */
    static createFrom($$source: any = {}): FindSomething {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType12;
        const $$createField6_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("JS" in $$parsedSource) {
            $$parsedSource["JS"] = $$createField0_0($$parsedSource["JS"]);
        }
        if ("APIRoute" in $$parsedSource) {
            $$parsedSource["APIRoute"] = $$createField1_0($$parsedSource["APIRoute"]);
        }
        if ("IP_URL" in $$parsedSource) {
            $$parsedSource["IP_URL"] = $$createField2_0($$parsedSource["IP_URL"]);
        }
        if ("IDCard" in $$parsedSource) {
            $$parsedSource["IDCard"] = $$createField3_0($$parsedSource["IDCard"]);
        }
        if ("Phone" in $$parsedSource) {
            $$parsedSource["Phone"] = $$createField4_0($$parsedSource["Phone"]);
        }
        if ("Email" in $$parsedSource) {
            $$parsedSource["Email"] = $$createField5_0($$parsedSource["Email"]);
        }
        if ("Sensitive" in $$parsedSource) {
            $$parsedSource["Sensitive"] = $$createField6_0($$parsedSource["Sensitive"]);
        }
        return new FindSomething($$parsedSource as Partial<FindSomething>);
    }
}

export class FofaSearchResult {
    "Error": boolean;
    "Message": string;
    "Size": number;
    "Results": Results[];

    /** Creates a new FofaSearchResult instance. */
    constructor($$source: Partial<FofaSearchResult> = {}) {
        if (!("Error" in $$source)) {
            this["Error"] = false;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("Results" in $$source)) {
            this["Results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FofaSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FofaSearchResult {
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Results" in $$parsedSource) {
            $$parsedSource["Results"] = $$createField3_0($$parsedSource["Results"]);
        }
        return new FofaSearchResult($$parsedSource as Partial<FofaSearchResult>);
    }
}

export class HunterComponent {
    "name": string;
    "version": string;

    /** Creates a new HunterComponent instance. */
    constructor($$source: Partial<HunterComponent> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HunterComponent instance from a string or object.
     */
    static createFrom($$source: any = {}): HunterComponent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HunterComponent($$parsedSource as Partial<HunterComponent>);
    }
}

export class HunterData {
    "account_type": string;
    "arr": HunterDataArr[];
    "consume_quota": string;
    "rest_quota": string;
    "syntax_prompt": string;
    "time": number;
    "total": number;

    /** Creates a new HunterData instance. */
    constructor($$source: Partial<HunterData> = {}) {
        if (!("account_type" in $$source)) {
            this["account_type"] = "";
        }
        if (!("arr" in $$source)) {
            this["arr"] = [];
        }
        if (!("consume_quota" in $$source)) {
            this["consume_quota"] = "";
        }
        if (!("rest_quota" in $$source)) {
            this["rest_quota"] = "";
        }
        if (!("syntax_prompt" in $$source)) {
            this["syntax_prompt"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HunterData instance from a string or object.
     */
    static createFrom($$source: any = {}): HunterData {
        const $$createField1_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arr" in $$parsedSource) {
            $$parsedSource["arr"] = $$createField1_0($$parsedSource["arr"]);
        }
        return new HunterData($$parsedSource as Partial<HunterData>);
    }
}

export class HunterDataArr {
    "as_org": string;
    "banner": string;
    "base_protocol": string;
    "city": string;
    "company": string;
    "component": HunterComponent[];
    "country": string;
    "domain": string;
    "ip": string;
    "is_risk": string;
    "is_risk_protocol": string;
    "is_web": string;
    "isp": string;
    "number": string;
    "os": string;
    "port": number;
    "protocol": string;
    "province": string;
    "status_code": number;
    "updated_at": string;
    "url": string;
    "web_title": string;

    /** Creates a new HunterDataArr instance. */
    constructor($$source: Partial<HunterDataArr> = {}) {
        if (!("as_org" in $$source)) {
            this["as_org"] = "";
        }
        if (!("banner" in $$source)) {
            this["banner"] = "";
        }
        if (!("base_protocol" in $$source)) {
            this["base_protocol"] = "";
        }
        if (!("city" in $$source)) {
            this["city"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = [];
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("is_risk" in $$source)) {
            this["is_risk"] = "";
        }
        if (!("is_risk_protocol" in $$source)) {
            this["is_risk_protocol"] = "";
        }
        if (!("is_web" in $$source)) {
            this["is_web"] = "";
        }
        if (!("isp" in $$source)) {
            this["isp"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("province" in $$source)) {
            this["province"] = "";
        }
        if (!("status_code" in $$source)) {
            this["status_code"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("web_title" in $$source)) {
            this["web_title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HunterDataArr instance from a string or object.
     */
    static createFrom($$source: any = {}): HunterDataArr {
        const $$createField5_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("component" in $$parsedSource) {
            $$parsedSource["component"] = $$createField5_0($$parsedSource["component"]);
        }
        return new HunterDataArr($$parsedSource as Partial<HunterDataArr>);
    }
}

/**
 * Hunter数据的结构体
 */
export class HunterResult {
    "code": number;
    "data": HunterData;
    "message": string;

    /** Creates a new HunterResult instance. */
    constructor($$source: Partial<HunterResult> = {}) {
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = (new HunterData());
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HunterResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HunterResult {
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new HunterResult($$parsedSource as Partial<HunterResult>);
    }
}

export class HunterTips {
    "code": number;
    "data": HunterTipsData;
    "message": string;

    /** Creates a new HunterTips instance. */
    constructor($$source: Partial<HunterTips> = {}) {
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = (new HunterTipsData());
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HunterTips instance from a string or object.
     */
    static createFrom($$source: any = {}): HunterTips {
        const $$createField1_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new HunterTips($$parsedSource as Partial<HunterTips>);
    }
}

export class HunterTipsApp {
    "name": string;
    "asset_num": number;
    "tags": string[];

    /** Creates a new HunterTipsApp instance. */
    constructor($$source: Partial<HunterTipsApp> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("asset_num" in $$source)) {
            this["asset_num"] = 0;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HunterTipsApp instance from a string or object.
     */
    static createFrom($$source: any = {}): HunterTipsApp {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new HunterTipsApp($$parsedSource as Partial<HunterTipsApp>);
    }
}

export class HunterTipsData {
    "app": HunterTipsApp[];
    "collect": any[];

    /** Creates a new HunterTipsData instance. */
    constructor($$source: Partial<HunterTipsData> = {}) {
        if (!("app" in $$source)) {
            this["app"] = [];
        }
        if (!("collect" in $$source)) {
            this["collect"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HunterTipsData instance from a string or object.
     */
    static createFrom($$source: any = {}): HunterTipsData {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField0_0($$parsedSource["app"]);
        }
        if ("collect" in $$parsedSource) {
            $$parsedSource["collect"] = $$createField1_0($$parsedSource["collect"]);
        }
        return new HunterTipsData($$parsedSource as Partial<HunterTipsData>);
    }
}

export class ISICollectionResult {
    "Query": string;

    /**
     * 搜索总数
     */
    "Total": number;

    /**
     * 搜索结果
     */
    "Items": string[];

    /**
     * 搜索链接
     */
    "Link": string;

    /**
     * 来源
     */
    "Source": string;

    /** Creates a new ISICollectionResult instance. */
    constructor($$source: Partial<ISICollectionResult> = {}) {
        if (!("Query" in $$source)) {
            this["Query"] = "";
        }
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }
        if (!("Link" in $$source)) {
            this["Link"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ISICollectionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ISICollectionResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField2_0($$parsedSource["Items"]);
        }
        return new ISICollectionResult($$parsedSource as Partial<ISICollectionResult>);
    }
}

export class InfoResult {
    /**
     * 任务ID
     */
    "TaskId": string;

    /**
     * 网站链接
     */
    "URL": string;

    /**
     * 协议
     */
    "Scheme": string;

    /**
     * 域名 或者 IP
     */
    "Host": string;
    "Port": number;
    "StatusCode": number;
    "Length": number;
    "Title": string;
    "Fingerprints": string[];
    "IsWAF": boolean;
    "WAF": string;
    "Detect": string;

    /**
     * 截图图片路径
     */
    "Screenshot": string;

    /** Creates a new InfoResult instance. */
    constructor($$source: Partial<InfoResult> = {}) {
        if (!("TaskId" in $$source)) {
            this["TaskId"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Scheme" in $$source)) {
            this["Scheme"] = "";
        }
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("StatusCode" in $$source)) {
            this["StatusCode"] = 0;
        }
        if (!("Length" in $$source)) {
            this["Length"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Fingerprints" in $$source)) {
            this["Fingerprints"] = [];
        }
        if (!("IsWAF" in $$source)) {
            this["IsWAF"] = false;
        }
        if (!("WAF" in $$source)) {
            this["WAF"] = "";
        }
        if (!("Detect" in $$source)) {
            this["Detect"] = "";
        }
        if (!("Screenshot" in $$source)) {
            this["Screenshot"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfoResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InfoResult {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Fingerprints" in $$parsedSource) {
            $$parsedSource["Fingerprints"] = $$createField8_0($$parsedSource["Fingerprints"]);
        }
        return new InfoResult($$parsedSource as Partial<InfoResult>);
    }
}

export class InfoSource {
    "Filed": string;
    "Source": string;

    /** Creates a new InfoSource instance. */
    constructor($$source: Partial<InfoSource> = {}) {
        if (!("Filed" in $$source)) {
            this["Filed"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfoSource instance from a string or object.
     */
    static createFrom($$source: any = {}): InfoSource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InfoSource($$parsedSource as Partial<InfoSource>);
    }
}

export class JSFindResult {
    "Target": string;
    "VulType": string;
    "Severity": string;
    "Source": string;
    "Method": string;
    "Request": string;
    "Response": string;
    "Length": number;
    "Filed": string;

    /** Creates a new JSFindResult instance. */
    constructor($$source: Partial<JSFindResult> = {}) {
        if (!("Target" in $$source)) {
            this["Target"] = "";
        }
        if (!("VulType" in $$source)) {
            this["VulType"] = "";
        }
        if (!("Severity" in $$source)) {
            this["Severity"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Method" in $$source)) {
            this["Method"] = "";
        }
        if (!("Request" in $$source)) {
            this["Request"] = "";
        }
        if (!("Response" in $$source)) {
            this["Response"] = "";
        }
        if (!("Length" in $$source)) {
            this["Length"] = 0;
        }
        if (!("Filed" in $$source)) {
            this["Filed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JSFindResult instance from a string or object.
     */
    static createFrom($$source: any = {}): JSFindResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JSFindResult($$parsedSource as Partial<JSFindResult>);
    }
}

export class JdkConfig {
    "name": string;
    "path": string;

    /** Creates a new JdkConfig instance. */
    constructor($$source: Partial<JdkConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JdkConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): JdkConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JdkConfig($$parsedSource as Partial<JdkConfig>);
    }
}

export class Miit {
    "API": string;

    /** Creates a new Miit instance. */
    constructor($$source: Partial<Miit> = {}) {
        if (!("API" in $$source)) {
            this["API"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Miit instance from a string or object.
     */
    static createFrom($$source: any = {}): Miit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Miit($$parsedSource as Partial<Miit>);
    }
}

export class Navigation {
    "Name": string;
    "Children": Children[];

    /** Creates a new Navigation instance. */
    constructor($$source: Partial<Navigation> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Children" in $$source)) {
            this["Children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Navigation instance from a string or object.
     */
    static createFrom($$source: any = {}): Navigation {
        const $$createField1_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Children" in $$parsedSource) {
            $$parsedSource["Children"] = $$createField1_0($$parsedSource["Children"]);
        }
        return new Navigation($$parsedSource as Partial<Navigation>);
    }
}

export class NetwordCard {
    "Name": string;
    "IP": string;

    /** Creates a new NetwordCard instance. */
    constructor($$source: Partial<NetwordCard> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IP" in $$source)) {
            this["IP"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetwordCard instance from a string or object.
     */
    static createFrom($$source: any = {}): NetwordCard {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetwordCard($$parsedSource as Partial<NetwordCard>);
    }
}

export class OfficialAccount {
    "Name": string;
    "Numbers": string;
    "Logo": string;
    "Qrcode": string;
    "Introduction": string;

    /** Creates a new OfficialAccount instance. */
    constructor($$source: Partial<OfficialAccount> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Numbers" in $$source)) {
            this["Numbers"] = "";
        }
        if (!("Logo" in $$source)) {
            this["Logo"] = "";
        }
        if (!("Qrcode" in $$source)) {
            this["Qrcode"] = "";
        }
        if (!("Introduction" in $$source)) {
            this["Introduction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OfficialAccount instance from a string or object.
     */
    static createFrom($$source: any = {}): OfficialAccount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OfficialAccount($$parsedSource as Partial<OfficialAccount>);
    }
}

export class PathTimes {
    "Path": string;
    "Times": number;

    /** Creates a new PathTimes instance. */
    constructor($$source: Partial<PathTimes> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Times" in $$source)) {
            this["Times"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathTimes instance from a string or object.
     */
    static createFrom($$source: any = {}): PathTimes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathTimes($$parsedSource as Partial<PathTimes>);
    }
}

export class QuakeData {
    "URL": string;
    "Components": string[];
    "Port": number;

    /**
     * 协议类型
     */
    "Protocol": string;
    "Host": string;
    "Title": string;

    /**
     * 备案单位名称
     */
    "IcpName": string;

    /**
     * 备案单位编号
     */
    "IcpNumber": string;

    /**
     * 证书申请单位
     */
    "CertName": string;

    /**
     * 图标地址
     */
    "FaviconURL": string;
    "IP": string;
    "Isp": string;
    "Position": string;

    /** Creates a new QuakeData instance. */
    constructor($$source: Partial<QuakeData> = {}) {
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Components" in $$source)) {
            this["Components"] = [];
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("Protocol" in $$source)) {
            this["Protocol"] = "";
        }
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("IcpName" in $$source)) {
            this["IcpName"] = "";
        }
        if (!("IcpNumber" in $$source)) {
            this["IcpNumber"] = "";
        }
        if (!("CertName" in $$source)) {
            this["CertName"] = "";
        }
        if (!("FaviconURL" in $$source)) {
            this["FaviconURL"] = "";
        }
        if (!("IP" in $$source)) {
            this["IP"] = "";
        }
        if (!("Isp" in $$source)) {
            this["Isp"] = "";
        }
        if (!("Position" in $$source)) {
            this["Position"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuakeData instance from a string or object.
     */
    static createFrom($$source: any = {}): QuakeData {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Components" in $$parsedSource) {
            $$parsedSource["Components"] = $$createField1_0($$parsedSource["Components"]);
        }
        return new QuakeData($$parsedSource as Partial<QuakeData>);
    }
}

export class QuakeResult {
    /**
     * 响应状态信息，正常是0
     */
    "Code": number;

    /**
     * 提示信息
     */
    "Message": string;
    "Data": QuakeData[];
    "Total": number;

    /**
     * 剩余积分
     */
    "Credit": number;

    /** Creates a new QuakeResult instance. */
    constructor($$source: Partial<QuakeResult> = {}) {
        if (!("Code" in $$source)) {
            this["Code"] = 0;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Data" in $$source)) {
            this["Data"] = [];
        }
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }
        if (!("Credit" in $$source)) {
            this["Credit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuakeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuakeResult {
        const $$createField2_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField2_0($$parsedSource["Data"]);
        }
        return new QuakeResult($$parsedSource as Partial<QuakeResult>);
    }
}

export class QuakeTipsData {
    "product_name": string;
    "vul_count": number;
    "vendor_name": string;
    "ip_count": number;

    /** Creates a new QuakeTipsData instance. */
    constructor($$source: Partial<QuakeTipsData> = {}) {
        if (!("product_name" in $$source)) {
            this["product_name"] = "";
        }
        if (!("vul_count" in $$source)) {
            this["vul_count"] = 0;
        }
        if (!("vendor_name" in $$source)) {
            this["vendor_name"] = "";
        }
        if (!("ip_count" in $$source)) {
            this["ip_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuakeTipsData instance from a string or object.
     */
    static createFrom($$source: any = {}): QuakeTipsData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuakeTipsData($$parsedSource as Partial<QuakeTipsData>);
    }
}

export class QuakeTipsResult {
    "code": number;
    "message": string;
    "data": QuakeTipsData[];

    /** Creates a new QuakeTipsResult instance. */
    constructor($$source: Partial<QuakeTipsResult> = {}) {
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuakeTipsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuakeTipsResult {
        const $$createField2_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new QuakeTipsResult($$parsedSource as Partial<QuakeTipsResult>);
    }
}

export class RawResponse {
    "Error": string;
    "StatusCode": number;
    "Response": string;
    "ResponseTime": number;

    /** Creates a new RawResponse instance. */
    constructor($$source: Partial<RawResponse> = {}) {
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }
        if (!("StatusCode" in $$source)) {
            this["StatusCode"] = 0;
        }
        if (!("Response" in $$source)) {
            this["Response"] = "";
        }
        if (!("ResponseTime" in $$source)) {
            this["ResponseTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RawResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): RawResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RawResponse($$parsedSource as Partial<RawResponse>);
    }
}

export class Response {
    "Error": boolean;
    "Proto": string;
    "StatsCode": number;
    "Header": { [_ in string]?: string };
    "Body": string;

    /** Creates a new Response instance. */
    constructor($$source: Partial<Response> = {}) {
        if (!("Error" in $$source)) {
            this["Error"] = false;
        }
        if (!("Proto" in $$source)) {
            this["Proto"] = "";
        }
        if (!("StatsCode" in $$source)) {
            this["StatsCode"] = 0;
        }
        if (!("Header" in $$source)) {
            this["Header"] = {};
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     */
    static createFrom($$source: any = {}): Response {
        const $$createField3_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField3_0($$parsedSource["Header"]);
        }
        return new Response($$parsedSource as Partial<Response>);
    }
}

export class Results {
    "URL": string;
    "Host": string;
    "Title": string;
    "Fid": string;
    "IP": string;
    "Port": string;
    "Domain": string;
    "Protocol": string;
    "Region": string;
    "ICP": string;
    "Product": string;

    /** Creates a new Results instance. */
    constructor($$source: Partial<Results> = {}) {
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Fid" in $$source)) {
            this["Fid"] = "";
        }
        if (!("IP" in $$source)) {
            this["IP"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = "";
        }
        if (!("Domain" in $$source)) {
            this["Domain"] = "";
        }
        if (!("Protocol" in $$source)) {
            this["Protocol"] = "";
        }
        if (!("Region" in $$source)) {
            this["Region"] = "";
        }
        if (!("ICP" in $$source)) {
            this["ICP"] = "";
        }
        if (!("Product" in $$source)) {
            this["Product"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Results instance from a string or object.
     */
    static createFrom($$source: any = {}): Results {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Results($$parsedSource as Partial<Results>);
    }
}

export class RowData {
    "Columns": string[];
    "Rows": any[][];
    "RowsCount": number;

    /** Creates a new RowData instance. */
    constructor($$source: Partial<RowData> = {}) {
        if (!("Columns" in $$source)) {
            this["Columns"] = [];
        }
        if (!("Rows" in $$source)) {
            this["Rows"] = [];
        }
        if (!("RowsCount" in $$source)) {
            this["RowsCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowData instance from a string or object.
     */
    static createFrom($$source: any = {}): RowData {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Columns" in $$parsedSource) {
            $$parsedSource["Columns"] = $$createField0_0($$parsedSource["Columns"]);
        }
        if ("Rows" in $$parsedSource) {
            $$parsedSource["Rows"] = $$createField1_0($$parsedSource["Rows"]);
        }
        return new RowData($$parsedSource as Partial<RowData>);
    }
}

export class SpaceEngineSyntax {
    "Name": string;
    "Content": string;

    /** Creates a new SpaceEngineSyntax instance. */
    constructor($$source: Partial<SpaceEngineSyntax> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpaceEngineSyntax instance from a string or object.
     */
    static createFrom($$source: any = {}): SpaceEngineSyntax {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpaceEngineSyntax($$parsedSource as Partial<SpaceEngineSyntax>);
    }
}

export class SpaceOption {
    "FofaApi": string;
    "FofaEmail": string;
    "FofaKey": string;
    "HunterKey": string;
    "QuakeKey": string;

    /** Creates a new SpaceOption instance. */
    constructor($$source: Partial<SpaceOption> = {}) {
        if (!("FofaApi" in $$source)) {
            this["FofaApi"] = "";
        }
        if (!("FofaEmail" in $$source)) {
            this["FofaEmail"] = "";
        }
        if (!("FofaKey" in $$source)) {
            this["FofaKey"] = "";
        }
        if (!("HunterKey" in $$source)) {
            this["HunterKey"] = "";
        }
        if (!("QuakeKey" in $$source)) {
            this["QuakeKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpaceOption instance from a string or object.
     */
    static createFrom($$source: any = {}): SpaceOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpaceOption($$parsedSource as Partial<SpaceOption>);
    }
}

/**
 * 返回后端执行状态
 * Error: true/false
 * Msg:   错误信息
 */
export class Status {
    "Error": boolean;
    "Msg": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("Error" in $$source)) {
            this["Error"] = false;
        }
        if (!("Msg" in $$source)) {
            this["Msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}

export class SubdomainOption {
    "Mode": number;
    "Domains": string[];
    "Subs": string[];
    "AppendEngines": string[];
    "FofaAddress": string;
    "FofaEmail": string;
    "FofaApi": string;
    "HunterApi": string;
    "QuakeApi": string;
    "ChaosApi": string;
    "ZoomeyeApi": string;
    "SecuritytrailsApi": string;
    "BevigilApi": string;
    "GithubApi": string;

    /**
     * 解析线程
     */
    "Thread": number;

    /**
     * 仅枚举模式启用时生效
     */
    "Timeout": number;

    /**
     * 解析过滤IP次数
     */
    "ResolveExcludeTimes": number;
    "DnsServers": string[];

    /** Creates a new SubdomainOption instance. */
    constructor($$source: Partial<SubdomainOption> = {}) {
        if (!("Mode" in $$source)) {
            this["Mode"] = 0;
        }
        if (!("Domains" in $$source)) {
            this["Domains"] = [];
        }
        if (!("Subs" in $$source)) {
            this["Subs"] = [];
        }
        if (!("AppendEngines" in $$source)) {
            this["AppendEngines"] = [];
        }
        if (!("FofaAddress" in $$source)) {
            this["FofaAddress"] = "";
        }
        if (!("FofaEmail" in $$source)) {
            this["FofaEmail"] = "";
        }
        if (!("FofaApi" in $$source)) {
            this["FofaApi"] = "";
        }
        if (!("HunterApi" in $$source)) {
            this["HunterApi"] = "";
        }
        if (!("QuakeApi" in $$source)) {
            this["QuakeApi"] = "";
        }
        if (!("ChaosApi" in $$source)) {
            this["ChaosApi"] = "";
        }
        if (!("ZoomeyeApi" in $$source)) {
            this["ZoomeyeApi"] = "";
        }
        if (!("SecuritytrailsApi" in $$source)) {
            this["SecuritytrailsApi"] = "";
        }
        if (!("BevigilApi" in $$source)) {
            this["BevigilApi"] = "";
        }
        if (!("GithubApi" in $$source)) {
            this["GithubApi"] = "";
        }
        if (!("Thread" in $$source)) {
            this["Thread"] = 0;
        }
        if (!("Timeout" in $$source)) {
            this["Timeout"] = 0;
        }
        if (!("ResolveExcludeTimes" in $$source)) {
            this["ResolveExcludeTimes"] = 0;
        }
        if (!("DnsServers" in $$source)) {
            this["DnsServers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubdomainOption instance from a string or object.
     */
    static createFrom($$source: any = {}): SubdomainOption {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Domains" in $$parsedSource) {
            $$parsedSource["Domains"] = $$createField1_0($$parsedSource["Domains"]);
        }
        if ("Subs" in $$parsedSource) {
            $$parsedSource["Subs"] = $$createField2_0($$parsedSource["Subs"]);
        }
        if ("AppendEngines" in $$parsedSource) {
            $$parsedSource["AppendEngines"] = $$createField3_0($$parsedSource["AppendEngines"]);
        }
        if ("DnsServers" in $$parsedSource) {
            $$parsedSource["DnsServers"] = $$createField17_0($$parsedSource["DnsServers"]);
        }
        return new SubdomainOption($$parsedSource as Partial<SubdomainOption>);
    }
}

export class TaskResult {
    "TaskId": string;
    "TaskName": string;
    "Targets": string;
    "Failed": number;
    "Vulnerability": number;

    /** Creates a new TaskResult instance. */
    constructor($$source: Partial<TaskResult> = {}) {
        if (!("TaskId" in $$source)) {
            this["TaskId"] = "";
        }
        if (!("TaskName" in $$source)) {
            this["TaskName"] = "";
        }
        if (!("Targets" in $$source)) {
            this["Targets"] = "";
        }
        if (!("Failed" in $$source)) {
            this["Failed"] = 0;
        }
        if (!("Vulnerability" in $$source)) {
            this["Vulnerability"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskResult($$parsedSource as Partial<TaskResult>);
    }
}

export class Tianyancha {
    "Enable": boolean;
    "Token": string;
    "Id": string;

    /** Creates a new Tianyancha instance. */
    constructor($$source: Partial<Tianyancha> = {}) {
        if (!("Enable" in $$source)) {
            this["Enable"] = false;
        }
        if (!("Token" in $$source)) {
            this["Token"] = "";
        }
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tianyancha instance from a string or object.
     */
    static createFrom($$source: any = {}): Tianyancha {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tianyancha($$parsedSource as Partial<Tianyancha>);
    }
}

export class TipsResult {
    "code": number;
    "message": string;
    "data": Data[];

    /** Creates a new TipsResult instance. */
    constructor($$source: Partial<TipsResult> = {}) {
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TipsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TipsResult {
        const $$createField2_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new TipsResult($$parsedSource as Partial<TipsResult>);
    }
}

export class VulnDashboard {
    "TotalTasks": number;
    "TotalVulnerabilities": number;
    "TotalFailed": number;
    "SeverityCritical": number;
    "SeverityHigh": number;
    "SeverityMedium": number;
    "SeverityLow": number;
    "SeverityInfo": number;
    "RecentTasks": TaskResult[];

    /** Creates a new VulnDashboard instance. */
    constructor($$source: Partial<VulnDashboard> = {}) {
        if (!("TotalTasks" in $$source)) {
            this["TotalTasks"] = 0;
        }
        if (!("TotalVulnerabilities" in $$source)) {
            this["TotalVulnerabilities"] = 0;
        }
        if (!("TotalFailed" in $$source)) {
            this["TotalFailed"] = 0;
        }
        if (!("SeverityCritical" in $$source)) {
            this["SeverityCritical"] = 0;
        }
        if (!("SeverityHigh" in $$source)) {
            this["SeverityHigh"] = 0;
        }
        if (!("SeverityMedium" in $$source)) {
            this["SeverityMedium"] = 0;
        }
        if (!("SeverityLow" in $$source)) {
            this["SeverityLow"] = 0;
        }
        if (!("SeverityInfo" in $$source)) {
            this["SeverityInfo"] = 0;
        }
        if (!("RecentTasks" in $$source)) {
            this["RecentTasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VulnDashboard instance from a string or object.
     */
    static createFrom($$source: any = {}): VulnDashboard {
        const $$createField8_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RecentTasks" in $$parsedSource) {
            $$parsedSource["RecentTasks"] = $$createField8_0($$parsedSource["RecentTasks"]);
        }
        return new VulnDashboard($$parsedSource as Partial<VulnDashboard>);
    }
}

export class VulnerabilityInfo {
    /**
     * 任务ID
     */
    "TaskId": string;
    "ID": string;
    "Name": string;
    "Description": string;
    "Reference": string;
    "Type": string;
    "Severity": string;
    "URL": string;
    "Request": string;
    "Response": string;
    "ResponseTime": string;
    "Extract": string;

    /** Creates a new VulnerabilityInfo instance. */
    constructor($$source: Partial<VulnerabilityInfo> = {}) {
        if (!("TaskId" in $$source)) {
            this["TaskId"] = "";
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Reference" in $$source)) {
            this["Reference"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Severity" in $$source)) {
            this["Severity"] = "";
        }
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Request" in $$source)) {
            this["Request"] = "";
        }
        if (!("Response" in $$source)) {
            this["Response"] = "";
        }
        if (!("ResponseTime" in $$source)) {
            this["ResponseTime"] = "";
        }
        if (!("Extract" in $$source)) {
            this["Extract"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VulnerabilityInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VulnerabilityInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VulnerabilityInfo($$parsedSource as Partial<VulnerabilityInfo>);
    }
}

export class WebReport {
    "Targets": string;
    "Fingerprints": InfoResult[];
    "POCs": VulnerabilityInfo[];

    /** Creates a new WebReport instance. */
    constructor($$source: Partial<WebReport> = {}) {
        if (!("Targets" in $$source)) {
            this["Targets"] = "";
        }
        if (!("Fingerprints" in $$source)) {
            this["Fingerprints"] = [];
        }
        if (!("POCs" in $$source)) {
            this["POCs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebReport instance from a string or object.
     */
    static createFrom($$source: any = {}): WebReport {
        const $$createField1_0 = $$createType37;
        const $$createField2_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Fingerprints" in $$parsedSource) {
            $$parsedSource["Fingerprints"] = $$createField1_0($$parsedSource["Fingerprints"]);
        }
        if ("POCs" in $$parsedSource) {
            $$parsedSource["POCs"] = $$createField2_0($$parsedSource["POCs"]);
        }
        return new WebReport($$parsedSource as Partial<WebReport>);
    }
}

export class WebscanOptions {
    "Target": string[];

    /**
     * tcp层的目标，兼容nuclei可以扫描
     */
    "TcpTarget": { [_ in string]?: string[] };
    "Thread": number;
    "Screenshot": boolean;
    "DeepScan": boolean;
    "RootPath": boolean;
    "CallNuclei": boolean;
    "Tags": string[];
    "TemplateFiles": string[];
    "SkipNucleiWithoutTags": boolean;

    /**
     * 开启后会将所有目标添加 Generate-Log4j2 的指纹
     */
    "GenerateLog4j2": boolean;

    /**
     * 追加模板文件夹
     */
    "AppendTemplateFolder": string;

    /**
     * 指定扫描网卡
     */
    "NetworkCard": string;

    /**
     * 自定义请求头
     */
    "CustomHeaders": string;

    /**
     * 主动扫描超时时间
     */
    "ActiveTimeout": number;

    /** Creates a new WebscanOptions instance. */
    constructor($$source: Partial<WebscanOptions> = {}) {
        if (!("Target" in $$source)) {
            this["Target"] = [];
        }
        if (!("TcpTarget" in $$source)) {
            this["TcpTarget"] = {};
        }
        if (!("Thread" in $$source)) {
            this["Thread"] = 0;
        }
        if (!("Screenshot" in $$source)) {
            this["Screenshot"] = false;
        }
        if (!("DeepScan" in $$source)) {
            this["DeepScan"] = false;
        }
        if (!("RootPath" in $$source)) {
            this["RootPath"] = false;
        }
        if (!("CallNuclei" in $$source)) {
            this["CallNuclei"] = false;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("TemplateFiles" in $$source)) {
            this["TemplateFiles"] = [];
        }
        if (!("SkipNucleiWithoutTags" in $$source)) {
            this["SkipNucleiWithoutTags"] = false;
        }
        if (!("GenerateLog4j2" in $$source)) {
            this["GenerateLog4j2"] = false;
        }
        if (!("AppendTemplateFolder" in $$source)) {
            this["AppendTemplateFolder"] = "";
        }
        if (!("NetworkCard" in $$source)) {
            this["NetworkCard"] = "";
        }
        if (!("CustomHeaders" in $$source)) {
            this["CustomHeaders"] = "";
        }
        if (!("ActiveTimeout" in $$source)) {
            this["ActiveTimeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebscanOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): WebscanOptions {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType40;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Target" in $$parsedSource) {
            $$parsedSource["Target"] = $$createField0_0($$parsedSource["Target"]);
        }
        if ("TcpTarget" in $$parsedSource) {
            $$parsedSource["TcpTarget"] = $$createField1_0($$parsedSource["TcpTarget"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField7_0($$parsedSource["Tags"]);
        }
        if ("TemplateFiles" in $$parsedSource) {
            $$parsedSource["TemplateFiles"] = $$createField8_0($$parsedSource["TemplateFiles"]);
        }
        return new WebscanOptions($$parsedSource as Partial<WebscanOptions>);
    }
}

export class WindowsSize {
    "Width": number;
    "Height": number;

    /** Creates a new WindowsSize instance. */
    constructor($$source: Partial<WindowsSize> = {}) {
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowsSize instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowsSize {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowsSize($$parsedSource as Partial<WindowsSize>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CompanyInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = App.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Applet.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = OfficialAccount.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = Tianyancha.createFrom;
const $$createType10 = Miit.createFrom;
const $$createType11 = InfoSource.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Results.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = HunterDataArr.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = HunterComponent.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = HunterData.createFrom;
const $$createType20 = HunterTipsData.createFrom;
const $$createType21 = HunterTipsApp.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($Create.Any);
const $$createType24 = Children.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = QuakeData.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = QuakeTipsData.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Map($Create.Any, $Create.Any);
const $$createType31 = $Create.Array($$createType23);
const $$createType32 = Data.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = TaskResult.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = InfoResult.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = VulnerabilityInfo.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = $Create.Map($Create.Any, $$createType0);
