// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Result {
    "URL": string;
    "IP": string;
    "Domain": string;
    "Port": string;
    "Protocol": string;
    "Title": string;
    "Components": string;
    "Source": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("IP" in $$source)) {
            this["IP"] = "";
        }
        if (!("Domain" in $$source)) {
            this["Domain"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = "";
        }
        if (!("Protocol" in $$source)) {
            this["Protocol"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Components" in $$source)) {
            this["Components"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}
