// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dirsearch$0 from "../core/dirsearch/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as space$0 from "../core/space/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as structs$0 from "../lib/structs/models.js";

export function AnalyzeAPI(homeURL: string, baseURL: string, apiList: string[], headers: { [_ in string]?: string }, lowPrivilegeHeaders: { [_ in string]?: string }, authentication: string[], highRiskRouter: string[]): $CancellablePromise<void> {
    return $Call.ByID(508375838, homeURL, baseURL, apiList, headers, lowPrivilegeHeaders, authentication, highRiskRouter);
}

/**
 * 返回 true 将导致应用程序继续，false 将继续正常关闭
 */
export function BeforeClose(): $CancellablePromise<boolean> {
    return $Call.ByID(358549635);
}

export function Callgologger(level: string, msg: string): $CancellablePromise<void> {
    return $Call.ByID(2070200536, level, msg);
}

export function EnrichCompanyWithMiit(company: structs$0.CompanyInfo | null, miitApi: string): $CancellablePromise<void> {
    return $Call.ByID(343003165, company, miitApi);
}

export function ExitScanner(scanType: string): $CancellablePromise<void> {
    return $Call.ByID(568765528, scanType);
}

export function ExportCompanyInfoToExcel(infos: structs$0.CompanyInfo[], reportpath: string): $CancellablePromise<boolean> {
    return $Call.ByID(3040167241, infos, reportpath);
}

export function ExtractAllJSLink(url: string): $CancellablePromise<string[]> {
    return $Call.ByID(2554764973, url).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * 允许目标传入文件或者目标favicon地址
 */
export function FaviconMd5(target: string): $CancellablePromise<string> {
    return $Call.ByID(4233465970, target);
}

export function FetchCompanyInfo(companyName: string, ratio: number, ds: structs$0.DataSource | null, maxDepth: number): $CancellablePromise<structs$0.CompanyInfo> {
    return $Call.ByID(2403454373, companyName, ratio, ds, maxDepth).then(($result: any) => {
        return $$createType1($result);
    });
}

export function FingerprintList(): $CancellablePromise<string[]> {
    return $Call.ByID(222479534).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FofaSearch(query: string, pageSzie: string, pageNum: string, address: string, email: string, key: string, fraud: boolean, cert: boolean, withFid: boolean): $CancellablePromise<structs$0.FofaSearchResult | null> {
    return $Call.ByID(249554960, query, pageSzie, pageNum, address, email, key, fraud, cert, withFid).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FofaTips(query: string): $CancellablePromise<structs$0.TipsResult | null> {
    return $Call.ByID(1035789854, query).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetFingerPocMap(): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(1226701119).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GitDorks(target: string, dork: string, apikey: string): $CancellablePromise<structs$0.ISICollectionResult | null> {
    return $Call.ByID(1129219605, target, dork, apikey).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GoFetch(method: string, target: string, body: any, headers: { [_ in string]?: string }, timeout: number, proxyURL: string): $CancellablePromise<structs$0.Response | null> {
    return $Call.ByID(2648229600, method, target, body, headers, timeout, proxyURL).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GoogleHackerBingSearch(query: string): $CancellablePromise<structs$0.ISICollectionResult | null> {
    return $Call.ByID(1866458921, query).then(($result: any) => {
        return $$createType8($result);
    });
}

export function HostAlive(targets: string[], Ping: boolean): $CancellablePromise<string[]> {
    return $Call.ByID(1817908037, targets, Ping).then(($result: any) => {
        return $$createType0($result);
    });
}

export function HunterSearch(api: string, key: string, query: string, pageSize: string, pageNum: string, times: string, asset: string, deduplication: boolean): $CancellablePromise<structs$0.HunterResult | null> {
    return $Call.ByID(170444876, api, key, query, pageSize, pageNum, times, asset, deduplication).then(($result: any) => {
        return $$createType12($result);
    });
}

export function HunterTips(query: string): $CancellablePromise<structs$0.HunterTips | null> {
    return $Call.ByID(4204035786, query).then(($result: any) => {
        return $$createType14($result);
    });
}

export function IconHash(target: string): $CancellablePromise<string> {
    return $Call.ByID(3436299143, target);
}

/**
 * 仅在执行时调用一次
 */
export function InitRule(appendTemplateFolder: string): $CancellablePromise<boolean> {
    return $Call.ByID(3464674446, appendTemplateFolder);
}

export function IpLocation(ip: string): $CancellablePromise<string> {
    return $Call.ByID(3279365724, ip);
}

export function JSFind(target: string, prefixJsURL: string, jsLinks: string[], blackDomainList: string[]): $CancellablePromise<structs$0.FindSomething> {
    return $Call.ByID(4007238694, target, prefixJsURL, jsLinks, blackDomainList).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * dirsearch
 */
export function LoadDirsearchDict(dictPath: string[], newExts: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(11425241, dictPath, newExts).then(($result: any) => {
        return $$createType0($result);
    });
}

export function NetDial(host: string): $CancellablePromise<boolean> {
    return $Call.ByID(3906009019, host);
}

/**
 * 端口暴破
 */
export function NewCrackScanenr(taskId: string, host: string, usernames: string[], passwords: string[]): $CancellablePromise<void> {
    return $Call.ByID(84436366, taskId, host, usernames, passwords);
}

export function NewDSStoreEngine(url: string): $CancellablePromise<string[]> {
    return $Call.ByID(2610707032, url).then(($result: any) => {
        return $$createType0($result);
    });
}

export function NewDirsearchScanner(options: dirsearch$0.Options): $CancellablePromise<void> {
    return $Call.ByID(2876295635, options);
}

export function NewTcpScanner(taskId: string, specialTargets: string[], ips: string[], ports: number[], thread: number, timeout: number, proxyURL: string): $CancellablePromise<void> {
    return $Call.ByID(270283195, taskId, specialTargets, ips, ports, thread, timeout, proxyURL);
}

/**
 * 多线程 Nuclei 扫描，由于Nucli的设计问题，多线程无法调用代理，否则会导致扫描失败
 */
export function NewWebScanner(taskId: string, options: structs$0.WebscanOptions, proxyURL: string, threadSafe: boolean): $CancellablePromise<void> {
    return $Call.ByID(3139551704, taskId, options, proxyURL, threadSafe);
}

export function QuakeSearch(ipList: string[], query: string, pageNum: number, pageSize: number, latest: boolean, invalid: boolean, honeypot: boolean, cdn: boolean, token: string, certcommon: string): $CancellablePromise<structs$0.QuakeResult | null> {
    return $Call.ByID(994481723, ipList, query, pageNum, pageSize, latest, invalid, honeypot, cdn, token, certcommon).then(($result: any) => {
        return $$createType17($result);
    });
}

export function QuakeTips(query: string): $CancellablePromise<structs$0.QuakeTipsResult | null> {
    return $Call.ByID(2208215085, query).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ResumeAfterHumanCheck(): $CancellablePromise<void> {
    return $Call.ByID(3677614110);
}

export function SendRequest(raw: string, forceHttps: boolean, redirect: boolean, proxyURL: string): $CancellablePromise<structs$0.RawResponse> {
    return $Call.ByID(1882671657, raw, forceHttps, redirect, proxyURL).then(($result: any) => {
        return $$createType20($result);
    });
}

export function Socks5Conn(ip: string, port: number, timeout: number, username: string, password: string, aliveURL: string): $CancellablePromise<boolean> {
    return $Call.ByID(1675532096, ip, port, timeout, username, password, aliveURL);
}

export function SpaceGetPort(ip: string): $CancellablePromise<number[]> {
    return $Call.ByID(1160970411, ip).then(($result: any) => {
        return $$createType21($result);
    });
}

export function Subdomain(o: structs$0.SubdomainOption): $CancellablePromise<void> {
    return $Call.ByID(2670310932, o);
}

export function UncoverSearch(query: string, types: string, option: structs$0.SpaceOption): $CancellablePromise<space$0.Result[]> {
    return $Call.ByID(2263366072, query, types, option).then(($result: any) => {
        return $$createType23($result);
    });
}

export function WriteCompanyInfoToJson(info: structs$0.CompanyInfo): $CancellablePromise<boolean> {
    return $Call.ByID(3017427959, info);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = structs$0.CompanyInfo.createFrom;
const $$createType2 = structs$0.FofaSearchResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = structs$0.TipsResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType0);
const $$createType7 = structs$0.ISICollectionResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = structs$0.Response.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = structs$0.HunterResult.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = structs$0.HunterTips.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = structs$0.FindSomething.createFrom;
const $$createType16 = structs$0.QuakeResult.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = structs$0.QuakeTipsResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = structs$0.RawResponse.createFrom;
const $$createType21 = $Create.Array($Create.Any);
const $$createType22 = space$0.Result.createFrom;
const $$createType23 = $Create.Array($$createType22);
