// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mongo$0 from "../../go.mongodb.org/mongo-driver/mongo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as structs$0 from "../lib/structs/models.js";

export function AddConnection(info: structs$0.DatabaseConnection): $CancellablePromise<boolean> {
    return $Call.ByID(2805962089, info);
}

/**
 * 添加指纹扫描结果
 */
export function AddFingerscanResult(result: structs$0.InfoResult): $CancellablePromise<boolean> {
    return $Call.ByID(1864442748, result);
}

/**
 * 添加漏洞扫描结果
 */
export function AddPocscanResult(result: structs$0.VulnerabilityInfo): $CancellablePromise<boolean> {
    return $Call.ByID(271306973, result);
}

/**
 * 添加任务记录
 */
export function AddScanTask(taskid: string, taskname: string, targets: string, failed: number, vulnerability: number): $CancellablePromise<boolean> {
    return $Call.ByID(4012387869, taskid, taskname, targets, failed, vulnerability);
}

export function ConnectDatabase(info: structs$0.DatabaseConnection): $CancellablePromise<boolean> {
    return $Call.ByID(811383625, info);
}

export function ConnectMongodb(host: string, user: string, pass: string): $CancellablePromise<mongo$0.Client | null> {
    return $Call.ByID(2117942950, host, user, pass).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateTable(): $CancellablePromise<boolean> {
    return $Call.ByID(3241790102);
}

export function DeleteAgentPool(host: string): $CancellablePromise<boolean> {
    return $Call.ByID(1059968792, host);
}

export function DeleteAllAgentPool(): $CancellablePromise<boolean> {
    return $Call.ByID(878315599);
}

export function DeleteRecordByPath(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3050693838, path);
}

/**
 * 执行 SQL 删除语句，删除 times 为 1 的记录
 */
export function DeleteRecordsWithTimesEqualOne(): $CancellablePromise<boolean> {
    return $Call.ByID(3369261957);
}

export function DisconnectDatabase(scheme: string): $CancellablePromise<boolean> {
    return $Call.ByID(150744149, scheme);
}

export function ExecSqlStatement(query: string, ...args: any[]): $CancellablePromise<boolean> {
    return $Call.ByID(2836976606, query, args);
}

export function ExportJSReportWithExcel(reportpath: string, results: structs$0.JSFindResult[]): $CancellablePromise<boolean> {
    return $Call.ByID(971073644, reportpath, results);
}

export function ExportWebReportWithExcel(reportpath: string, tasks: structs$0.TaskResult[]): $CancellablePromise<boolean> {
    return $Call.ByID(506619987, reportpath, tasks);
}

/**
 * 导出HTML报告
 */
export function ExportWebReportWithHtml(reportpath: string, taskids: string[]): $CancellablePromise<boolean> {
    return $Call.ByID(1756626973, reportpath, taskids);
}

/**
 * 导出JSON报告
 */
export function ExportWebReportWithJson(reportpath: string, tasks: structs$0.TaskResult[]): $CancellablePromise<boolean> {
    return $Call.ByID(2107052042, reportpath, tasks);
}

export function FetchDatabaseInfoFromOracle(): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(1182083341).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FetchDatabaseInfoFromPostgres(info: structs$0.DatabaseConnection): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(1569993556, info).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FetchDatabaseinfoFromMongodb(): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(2955162675).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FetchDatabaseinfoFromMysql(): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(2839429047).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FetchDatabaseinfoFromSqlServer(): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(3370889758).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FetchTableInfoFromMysql(dbName: string, tableName: string): $CancellablePromise<structs$0.RowData> {
    return $Call.ByID(2523932400, dbName, tableName).then(($result: any) => {
        return $$createType4($result);
    });
}

export function FetchTableInfoFromOracle(schemaName: string, tableName: string): $CancellablePromise<structs$0.RowData> {
    return $Call.ByID(3453127320, schemaName, tableName).then(($result: any) => {
        return $$createType4($result);
    });
}

export function FetchTableInfoFromPostgres(schemaName: string, tableName: string): $CancellablePromise<structs$0.RowData> {
    return $Call.ByID(1295682421, schemaName, tableName).then(($result: any) => {
        return $$createType4($result);
    });
}

export function FetchTableInfoFromSqlServer(dbName: string, tableName: string): $CancellablePromise<structs$0.RowData> {
    return $Call.ByID(23166545, dbName, tableName).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetAllDatabaseConnections(): $CancellablePromise<structs$0.DatabaseConnection[]> {
    return $Call.ByID(2920329973).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetAllPathsAndTimes(): $CancellablePromise<structs$0.PathTimes[]> {
    return $Call.ByID(3530218962).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * 风险目标 Top
 */
export function GetTopRiskTargets(): $CancellablePromise<structs$0.TaskResult[]> {
    return $Call.ByID(3870986440).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * 仪表盘数据汇总
 */
export function GetVulnDashboard(): $CancellablePromise<structs$0.VulnDashboard> {
    return $Call.ByID(612833815).then(($result: any) => {
        return $$createType11($result);
    });
}

export function InsertAgentPool(host: string): $CancellablePromise<boolean> {
    return $Call.ByID(2255862946, host);
}

export function InsertFavGrammarFiled($module: string, name: string, content: string): $CancellablePromise<boolean> {
    return $Call.ByID(599347249, $module, name, content);
}

/**
 * 加载JSON报告
 */
export function ReadWebReportWithJson(reportpath: string): $CancellablePromise<structs$0.WebReport> {
    return $Call.ByID(2104558904, reportpath).then(($result: any) => {
        return $$createType12($result);
    });
}

export function RemoveConnection(nanoid: string): $CancellablePromise<boolean> {
    return $Call.ByID(3473093830, nanoid);
}

export function RemoveFavGrammarFiled($module: string, name: string, content: string): $CancellablePromise<boolean> {
    return $Call.ByID(1024851442, $module, name, content);
}

/**
 * 移除某组指纹信息，用于删除探测http的基本状态，后续会由指纹探测重新写入
 */
export function RemoveFingerprintResult(taskid: string, link: string[]): $CancellablePromise<boolean> {
    return $Call.ByID(1607788531, taskid, link);
}

/**
 * 移除某个漏洞
 */
export function RemovePocscanResult(taskid: string, template_id: string, vuln_url: string): $CancellablePromise<boolean> {
    return $Call.ByID(3874839360, taskid, template_id, vuln_url);
}

/**
 * 移除扫描记录
 */
export function RemoveScanTask(taskid: string): $CancellablePromise<boolean> {
    return $Call.ByID(2490548974, taskid);
}

/**
 * 重命名任务
 */
export function RenameScanTask(taskid: string, taskname: string): $CancellablePromise<boolean> {
    return $Call.ByID(2269396248, taskid, taskname);
}

/**
 * 检索所有扫描记录
 */
export function RetrieveAllScanTasks(): $CancellablePromise<structs$0.TaskResult[]> {
    return $Call.ByID(819155914).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * 根据taskid检索指纹扫描的结果
 */
export function RetrieveFingerscanResults(taskid: string): $CancellablePromise<structs$0.InfoResult[]> {
    return $Call.ByID(3754767396, taskid).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * 根据taskid检索漏洞扫描记录
 */
export function RetrievePocscanResults(taskid: string): $CancellablePromise<structs$0.VulnerabilityInfo[]> {
    return $Call.ByID(3624602973, taskid).then(($result: any) => {
        return $$createType16($result);
    });
}

export function SaveWindowsScreenSize(width: number, height: number): $CancellablePromise<boolean> {
    return $Call.ByID(1138041061, width, height);
}

export function SelectAllAgentPool(): $CancellablePromise<string[]> {
    return $Call.ByID(839672740).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SelectAllSyntax($module: string): $CancellablePromise<structs$0.SpaceEngineSyntax[]> {
    return $Call.ByID(3311203338, $module).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SelectWindowsSize(): $CancellablePromise<structs$0.WindowsSize> {
    return $Call.ByID(2778810754).then(($result: any) => {
        return $$createType19($result);
    });
}

export function UpdateConnection(info: structs$0.DatabaseConnection): $CancellablePromise<boolean> {
    return $Call.ByID(3780430375, info);
}

export function UpdateOrInsertPath(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(801337392, path);
}

/**
 * 修改扫描结果 - 失败数量，漏洞数量
 */
export function UpdateScanTaskWithResults(taskid: string, failed: number, vulnerability: number): $CancellablePromise<boolean> {
    return $Call.ByID(2408156587, taskid, failed, vulnerability);
}

// Private type creation functions
const $$createType0 = mongo$0.Client.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = structs$0.RowData.createFrom;
const $$createType5 = structs$0.DatabaseConnection.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = structs$0.PathTimes.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = structs$0.TaskResult.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = structs$0.VulnDashboard.createFrom;
const $$createType12 = structs$0.WebReport.createFrom;
const $$createType13 = structs$0.InfoResult.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = structs$0.VulnerabilityInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = structs$0.SpaceEngineSyntax.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = structs$0.WindowsSize.createFrom;
