// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * hikvision
 */
export function CVE_2017_7921(url: string, proxyURL: string): $CancellablePromise<string> {
    return $Call.ByID(4077440163, url, proxyURL);
}

export function CVE_2021_29441_AddUser(url: string, headers: { [_ in string]?: string }, username: string, password: string, proxyURL: string): $CancellablePromise<string> {
    return $Call.ByID(3251213268, url, headers, username, password, proxyURL);
}

export function CVE_2021_29441_DelUser(url: string, headers: { [_ in string]?: string }, username: string, proxyURL: string): $CancellablePromise<string> {
    return $Call.ByID(1482372910, url, headers, username, proxyURL);
}

export function CVE_2021_29442(url: string, headers: { [_ in string]?: string }, proxyURL: string): $CancellablePromise<string> {
    return $Call.ByID(279869470, url, headers, proxyURL);
}

export function CVE_2021_36260(url: string, cmd: string, proxyURL: string): $CancellablePromise<string> {
    return $Call.ByID(302367200, url, cmd, proxyURL);
}

export function CameraCrackPassword(url: string, username: string, passwordList: string[]): $CancellablePromise<string> {
    return $Call.ByID(1782620996, url, username, passwordList);
}

export function FineReportChannelDeserialize(url: string, cmd: string, proxyURL: string): $CancellablePromise<string> {
    return $Call.ByID(787334202, url, cmd, proxyURL);
}
