// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * File struct 文件操作
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as structs$0 from "../lib/structs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AutoGenerateFavicon(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(437673113, filePath);
}

export function BuildTree(root: string, keywords: string[], blackList: string[]): $CancellablePromise<$models.Tree> {
    return $Call.ByID(4034424969, root, keywords, blackList).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CheckFileStat(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1403412961, path);
}

export function DirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(726176298);
}

export function DownloadLastestClient(): $CancellablePromise<structs$0.Status> {
    return $Call.ByID(1564958930).then(($result: any) => {
        return $$createType1($result);
    });
}

export function FileDialog(ext: string): $CancellablePromise<string> {
    return $Call.ByID(3133049129, ext);
}

export function FilepathJoin(paths: string[]): $CancellablePromise<string> {
    return $Call.ByID(852162610, paths);
}

/**
 * 读取本读图片
 */
export function GenerateFaviconBase64(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2655135571, filePath);
}

/**
 * 从网址获取到图标后保存在本地，并返回保存路径
 * 为了防止图片过大，还需要压缩图片
 */
export function GenerateFaviconBase64WithOnline(rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(1826049212, rawURL);
}

/**
 * 获取系统变量配置文件内容，主要用于配置JDK环境变量
 */
export function GetJdkConfig(): $CancellablePromise<structs$0.JdkConfig[] | null> {
    return $Call.ByID(179492878).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetLocalNaConfig(): $CancellablePromise<structs$0.Navigation[] | null> {
    return $Call.ByID(1401085419).then(($result: any) => {
        return $$createType7($result);
    });
}

export function InitConfig(warehouse: string): $CancellablePromise<boolean> {
    return $Call.ByID(2026776199, warehouse);
}

export function InitMemo(filepath: string, content: string): $CancellablePromise<boolean> {
    return $Call.ByID(2891758595, filepath, content);
}

export function InsetGroupNavigation(n: structs$0.Navigation): $CancellablePromise<boolean> {
    return $Call.ByID(2558736797, n);
}

export function InsetItemNavigation(groupName: string, child: structs$0.Children): $CancellablePromise<boolean> {
    return $Call.ByID(4102295369, groupName, child);
}

export function InsetJdkConfig(jdk: structs$0.JdkConfig): $CancellablePromise<boolean> {
    return $Call.ByID(1786778165, jdk);
}

export function IsMacOS(): $CancellablePromise<boolean> {
    return $Call.ByID(152535820);
}

export function List(folders: string[]): $CancellablePromise<$models.FileListInfo[]> {
    return $Call.ByID(380676739, folders).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListDir(folder: string): $CancellablePromise<string[]> {
    return $Call.ByID(162996994, folder).then(($result: any) => {
        return $$createType10($result);
    });
}

export function NetworkCardInfo(): $CancellablePromise<structs$0.NetwordCard[]> {
    return $Call.ByID(328479605).then(($result: any) => {
        return $$createType12($result);
    });
}

export function OpenFolder(filepath: string): $CancellablePromise<string> {
    return $Call.ByID(25567891, filepath);
}

/**
 * 给定一个路径，在打开所在文件夹的命令行
 */
export function OpenTerminal(filepath: string): $CancellablePromise<string> {
    return $Call.ByID(1006242587, filepath);
}

export function Path(p: string): $CancellablePromise<$models.PathInfo> {
    return $Call.ByID(2603858444, p).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ReadFile(filename: string): $CancellablePromise<$models.FileInfo | null> {
    return $Call.ByID(3827413761, filename).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ReadLocalStore(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3635239519).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ReadMemo(filepath: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1346281385, filepath).then(($result: any) => {
        return $$createType17($result);
    });
}

export function RemoveFile(file: string): $CancellablePromise<boolean> {
    return $Call.ByID(1000986265, file);
}

/**
 * windows要移除.xxx.old文件
 * mac需要推出挂载
 */
export function RemoveOldClient(): $CancellablePromise<void> {
    return $Call.ByID(3607743079);
}

export function RemoveOldConfig(): $CancellablePromise<void> {
    return $Call.ByID(3219585606);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2189050546);
}

export function RunApp(item: structs$0.Children): $CancellablePromise<void> {
    return $Call.ByID(147696895, item);
}

export function SaveDataToFile(data: any): $CancellablePromise<boolean> {
    return $Call.ByID(1698609893, data);
}

/**
 * selection会返回保存的文件路径+文件名 例如/Users/xxx/Downloads/test.xlsx
 */
export function SaveFileDialog(filename: string): $CancellablePromise<string> {
    return $Call.ByID(1022967808, filename);
}

export function SaveJdkConfig(jdks: structs$0.JdkConfig[]): $CancellablePromise<boolean> {
    return $Call.ByID(773237891, jdks);
}

export function SaveNavigation(n: structs$0.Navigation[]): $CancellablePromise<boolean> {
    return $Call.ByID(3106140380, n);
}

export function SaveToTempFile(content: string): $CancellablePromise<string> {
    return $Call.ByID(3221496331, content);
}

export function UpdatePocFile(warehouse: string, version: string): $CancellablePromise<boolean> {
    return $Call.ByID(3836244694, warehouse, version);
}

/**
 * 开始就要检测
 */
export function UserHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(943983486);
}

export function WriteFile(filetype: string, path: string, content: string): $CancellablePromise<boolean> {
    return $Call.ByID(51430280, filetype, path, content);
}

// Private type creation functions
const $$createType0 = $models.Tree.createFrom;
const $$createType1 = structs$0.Status.createFrom;
const $$createType2 = structs$0.JdkConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = structs$0.Navigation.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.FileListInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = structs$0.NetwordCard.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.PathInfo.createFrom;
const $$createType14 = $models.FileInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
