// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileInfo {
    "Error": boolean;
    "Message": string;
    "Content": string;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("Error" in $$source)) {
            this["Error"] = false;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

export class FileListInfo {
    /**
     * 完整路径
     */
    "Path": string;

    /**
     * 带名称后缀
     */
    "Name": string;

    /**
     * 基础名称
     */
    "BaseName": string;

    /**
     * 修改时间
     */
    "ModTime": string;

    /**
     * 大小
     */
    "Size": number;

    /** Creates a new FileListInfo instance. */
    constructor($$source: Partial<FileListInfo> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("BaseName" in $$source)) {
            this["BaseName"] = "";
        }
        if (!("ModTime" in $$source)) {
            this["ModTime"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileListInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileListInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileListInfo($$parsedSource as Partial<FileListInfo>);
    }
}

/**
 * 传入路径获取到的信息
 */
export class PathInfo {
    "Name": string;
    "Ext": string;
    "Dir": string;

    /** Creates a new PathInfo instance. */
    constructor($$source: Partial<PathInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Ext" in $$source)) {
            this["Ext"] = "";
        }
        if (!("Dir" in $$source)) {
            this["Dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PathInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathInfo($$parsedSource as Partial<PathInfo>);
    }
}

export class Tree {
    "id": string;
    "label": string;
    "isDir": boolean;

    /**
     * 记录命中次数
     */
    "hits"?: { [_ in string]?: number };
    "children"?: Tree[];

    /** Creates a new Tree instance. */
    constructor($$source: Partial<Tree> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tree instance from a string or object.
     */
    static createFrom($$source: any = {}): Tree {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField3_0($$parsedSource["hits"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new Tree($$parsedSource as Partial<Tree>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Tree.createFrom;
const $$createType2 = $Create.Array($$createType1);
