// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Client is a handle representing a pool of connections to a MongoDB deployment. It is safe for concurrent use by
 * multiple goroutines.
 * 
 * The Client type opens and closes connections automatically and maintains a pool of idle connections. For
 * connection pool configuration options, see documentation for the ClientOptions type in the mongo/options package.
 */
export class Client {

    /** Creates a new Client instance. */
    constructor($$source: Partial<Client> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     */
    static createFrom($$source: any = {}): Client {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client($$parsedSource as Partial<Client>);
    }
}
